const endpoints = {
    // Court
    GET_COURT_STATS_URL : "/court/stats",
    GET_ALL_COURTS_URL : "/court/all",
    GET_ACTIVE_COURTS_URL : "/court/active",
    GET_PASSIVE_COURTS_URL : "/court/passive",
    GET_DELETED_COURTS_URL : "/court/deleted",
    GET_ALL_SUB_COURTS_URL : "/court/{id}/subs/all",
    GET_ACTIVE_SUB_COURTS_URL : "/court/{id}/subs/active",
    GET_PASSIVE_SUB_COURTS_URL : "/court/{id}/subs/passive",
    GET_DELETED_SUB_COURTS_URL : "/court/{id}/subs/deleted",
    GET_COURT_URL : "/court/{id}",
    CREATE_COURT_URL : "/court",
    UPDATE_COURT_URL : "/court",
    SET_ACTIVE_COURT_URL : "/court/{id}/setActive",
    SET_PASSIVE_COURT_URL : "/court/{id}/setPassive",
    DELETE_COURT_URL : "/court/{id}",
    GET_SUB_COURTS_STATS_URL : "/court/{id}/stats",

    // Company
    GET_COMPANY_STATS_URL : "/company/stats",
    GET_ALL_COMPANIES_URL : "/company/all",
    GET_ACTIVE_COMPANIES_URL : "/company/active",
    GET_PASSIVE_COMPANIES_URL : "/company/passive",
    GET_DELETED_COMPANIES_URL : "/company/deleted",
    GET_COMPANY_URL : "/company/{id}",
    CREATE_COMPANY_URL : "/company",
    UPDATE_COMPANY_URL : "/company",
    SET_ACTIVE_COMPANY_URL : "/company/{id}/setActive",
    SET_PASSIVE_COMPANY_URL : "/company/{id}/setPassive",
    DELETE_COMPANY_URL : "/company/{id}",

    // Plan
    GET_PLAN_STATS_URL : "/plan/stats",
    GET_ALL_PLANS_URL : "/plan/all",
    GET_ACTIVE_PLANS_URL : "/plan/active",
    GET_PASSIVE_PLANS_URL : "/plan/passive",
    GET_DELETED_PLANS_URL : "/plan/deleted",
    GET_PLAN_URL : "/plan/{id}",
    CREATE_PLAN_URL : "/plan",
    UPDATE_PLAN_URL : "/plan",
    SET_ACTIVE_PLAN_URL : "/plan/{id}/setActive",
    SET_PASSIVE_PLAN_URL : "/plan/{id}/setPassive",
    DELETE_PLAN_URL : "/plan/{id}",

    // User
    GET_ADMIN_STATS_URL : "/user/admins/stats",
    GET_ALL_ADMINS_URL : "/user/admins/all",
    GET_ACTIVE_ADMINS_URL : "/user/admins/active",
    GET_PASSIVE_ADMINS_URL : "/user/admins/passive",
    GET_DELETED_ADMINS_URL : "/user/admins/deleted",
    GET_USER_URL : "/user/{id}",
    CREATE_USER_URL : "/user",
    UPDATE_USER_URL : "/user",
    SET_ACTIVE_USER_URL : "/user/{id}/setActive",
    SET_PASSIVE_USER_URL : "/user/{id}/setPassive",
    DELETE_USER_URL : "/user/{id}",

    // Lawyer
    GET_LAWYER_STATS_URL : "/lawyer/stats",
    GET_ALL_LAWYERS_URL : "/lawyer/all",
    GET_ACTIVE_LAWYERS_URL : "/lawyer/active",
    GET_PASSIVE_LAWYERS_URL : "/lawyer/passive",
    GET_DELETED_LAWYERS_URL : "/lawyer/deleted",
    GET_LAWYER_URL : "/lawyer/{id}",
    CREATE_LAWYER_URL : "/lawyer",
    UPDATE_LAWYER_URL : "/lawyer",
    SET_ACTIVE_LAWYER_URL : "/lawyer/{id}/setActive",
    SET_PASSIVE_LAWYER_URL : "/lawyer/{id}/setPassive",
    DELETE_LAWYER_URL : "/lawyer/{id}",

    // Client
    GET_CLIENT_STATS_URL : "/client/stats",
    GET_ALL_CLIENTS_URL : "/client/all",
    GET_ACTIVE_CLIENTS_URL : "/client/active",
    GET_PASSIVE_CLIENTS_URL : "/client/passive",
    GET_DELETED_CLIENTS_URL : "/client/deleted",
    GET_CLIENT_URL : "/client/{id}",
    CREATE_CLIENT_URL : "/client",
    UPDATE_CLIENT_URL : "/client",
    SET_ACTIVE_CLIENT_URL : "/client/{id}/setActive",
    SET_PASSIVE_CLIENT_URL : "/client/{id}/setPassive",
    DELETE_CLIENT_URL : "/client/{id}",

    // Subscription
    GET_SUBSCRIPTION_STATS_URL : "/subscription/stats",
    GET_ALL_SUBSCRIPTIONS_URL : "/subscription/all",
    GET_ACTIVE_SUBSCRIPTIONS_URL : "/subscription/active",
    GET_PASSIVE_SUBSCRIPTIONS_URL : "/subscription/passive",
    GET_DELETED_SUBSCRIPTIONS_URL : "/subscription/deleted",
    GET_SUBSCRIPTION_URL : "/subscription/{id}",
    CREATE_SUBSCRIPTION_URL : "/subscription",
    UPDATE_SUBSCRIPTION_URL : "/subscription",
    SET_ACTIVE_SUBSCRIPTION_URL : "/subscription/{id}/setActive",
    SET_PASSIVE_SUBSCRIPTION_URL : "/subscription/{id}/setPassive",
    DELETE_SUBSCRIPTION_URL : "/subscription/{id}",
}

export default endpoints;